modLoader="javafml"
loaderVersion="[33,)"
license="All rights reserved"
[[mods]]
modId="omnis"
version="${file.jarVersion}"
displayName="Omnis"
logoFile="omnis.png"
credits='''The Minecraft Modding Discord and everyone there.
It's an amazing place full of a ton of amazing people, this mod wouldn't be possible without them.

'''
authors="Sammy; and Queso"
description='''
Omnis adds cool loot!;
'''
[[dependencies.omnis]]
modId="forge"
mandatory=true
versionRange="[34.0.5,)"
ordering="NONE"
side="BOTH"

[[dependencies.omnis]]
modId="curios"
mandatory=true
versionRange="[1.16.3-4.0.1.0,)"
ordering="AFTER"
side="BOTH"